ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'insurance';
ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'education';
ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'energy';
ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'retail';
ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'media';
ALTER TYPE "sector" ADD VALUE IF NOT EXISTS 'transport';
