- generic [active] [ref=e1]:
  - alert [ref=e2]
  - generic [ref=e4]:
    - heading "OpenDoor" [level=1] [ref=e5]
    - paragraph [ref=e6]: Sign in to your LLM Gateway
    - generic [ref=e7]:
      - button "Email & Password" [ref=e8] [cursor=pointer]
      - button "Enterprise SSO" [ref=e9] [cursor=pointer]
    - generic [ref=e10]:
      - generic [ref=e11]:
        - generic [ref=e12]: Email
        - textbox [ref=e13]
      - generic [ref=e14]:
        - generic [ref=e15]: Password
        - textbox [ref=e16]
      - button "Sign In" [ref=e17] [cursor=pointer]:
        - img [ref=e18]
        - text: Sign In