import { Hono } from "hono";
import { requireTenant } from "../lib/platform.js";

const catalogRouter = new Hono();

export const PLATFORM_ENDPOINTS = [
  { method: "GET", path: "/v1/catalog", group: "meta", summary: "List every API-key endpoint" },
  { method: "GET", path: "/v1/account", group: "account", summary: "Org, plan, add-ons, and this key" },
  { method: "GET", path: "/v1/account/balance", group: "account", summary: "Spendable credit buckets" },
  { method: "GET", path: "/v1/usage", group: "account", summary: "Usage totals billed to this org" },
  { method: "GET", path: "/v1/usage/rate-limits", group: "account", summary: "Live RPM/TPM remaining" },
  { method: "GET", path: "/v1/requests", group: "account", summary: "Request log for this org" },
  { method: "GET", path: "/v1/requests/:id", group: "account", summary: "One request / generation" },
  { method: "GET", path: "/v1/keys", group: "account", summary: "List API keys" },
  { method: "POST", path: "/v1/keys", group: "account", summary: "Create an API key (secret shown once)" },
  { method: "DELETE", path: "/v1/keys/:id", group: "account", summary: "Revoke an API key" },
  { method: "POST", path: "/v1/chat/completions", group: "ai", summary: "Chat completions (usage-billed)" },
  { method: "POST", path: "/v1/completions", group: "ai", summary: "Text completions" },
  { method: "POST", path: "/v1/responses", group: "ai", summary: "Responses API" },
  { method: "POST", path: "/v1/embeddings", group: "ai", summary: "Embeddings" },
  { method: "POST", path: "/v1/rerank", group: "ai", summary: "Rerank documents" },
  { method: "GET", path: "/v1/models", group: "ai", summary: "Live model catalog" },
  { method: "GET", path: "/v1/models/:model", group: "ai", summary: "One model" },
  { method: "GET", path: "/v1/generation/:id", group: "ai", summary: "Look up a generation" },
  { method: "POST", path: "/v1/images/generations", group: "media", summary: "Generate images" },
  { method: "POST", path: "/v1/videos/generations", group: "media", summary: "Generate videos" },
  { method: "GET", path: "/v1/videos/generations/:id", group: "media", summary: "Poll a video job" },
  { method: "POST", path: "/v1/audio/transcriptions", group: "media", summary: "Transcribe audio" },
  { method: "POST", path: "/v1/audio/speech", group: "media", summary: "Text to speech" },
  { method: "POST", path: "/v1/files", group: "files", summary: "Upload a file" },
  { method: "GET", path: "/v1/files", group: "files", summary: "List files" },
  { method: "GET", path: "/v1/files/:id", group: "files", summary: "Get file metadata" },
  { method: "GET", path: "/v1/files/:id/content", group: "files", summary: "Download file text/bytes" },
  { method: "DELETE", path: "/v1/files/:id", group: "files", summary: "Delete a file" },
  { method: "POST", path: "/v1/batches", group: "files", summary: "Create a batch" },
  { method: "GET", path: "/v1/batches", group: "files", summary: "List batches" },
  { method: "GET", path: "/v1/batches/:id", group: "files", summary: "Get a batch" },
  { method: "POST", path: "/v1/plugins/web-search", group: "plugins", summary: "Live web search (add-on)" },
  { method: "GET", path: "/v1/assistants", group: "assistants", summary: "List assistants" },
  { method: "POST", path: "/v1/assistants", group: "assistants", summary: "Create an assistant" },
  { method: "GET", path: "/v1/assistants/:id", group: "assistants", summary: "Get an assistant" },
  { method: "PATCH", path: "/v1/assistants/:id", group: "assistants", summary: "Update an assistant" },
  { method: "DELETE", path: "/v1/assistants/:id", group: "assistants", summary: "Disable an assistant" },
  { method: "POST", path: "/v1/assistants/:id/chat", group: "assistants", summary: "Run the assistant (usage-billed)" },
  { method: "GET", path: "/v1/workflows", group: "workflows", summary: "List workflows" },
  { method: "POST", path: "/v1/workflows", group: "workflows", summary: "Create a workflow" },
  { method: "GET", path: "/v1/workflows/:id", group: "workflows", summary: "Get a workflow" },
  { method: "PATCH", path: "/v1/workflows/:id", group: "workflows", summary: "Update a workflow" },
  { method: "DELETE", path: "/v1/workflows/:id", group: "workflows", summary: "Delete a workflow" },
  { method: "POST", path: "/v1/workflows/:id/run", group: "workflows", summary: "Run a workflow (usage-billed)" },
  { method: "GET", path: "/v1/workflows/:id/runs", group: "workflows", summary: "List workflow runs" },
  { method: "GET", path: "/v1/training/datasets", group: "training", summary: "List datasets" },
  { method: "POST", path: "/v1/training/datasets", group: "training", summary: "Create a dataset" },
  { method: "GET", path: "/v1/training/jobs", group: "training", summary: "List training jobs" },
  { method: "POST", path: "/v1/training/jobs", group: "training", summary: "Queue a training job" },
  { method: "GET", path: "/v1/training/jobs/:id", group: "training", summary: "Get a training job" },
  { method: "GET", path: "/v1/deployments", group: "capacity", summary: "List deployments" },
  { method: "POST", path: "/v1/deployments", group: "capacity", summary: "Create a deployment record" },
  { method: "GET", path: "/v1/deployments/:id", group: "capacity", summary: "Get a deployment" },
  { method: "DELETE", path: "/v1/deployments/:id", group: "capacity", summary: "Stop a deployment" },
  { method: "GET", path: "/v1/premium/rentals", group: "capacity", summary: "List private GPU rentals" },
  { method: "POST", path: "/v1/premium/rentals", group: "capacity", summary: "Start a rental" },
  { method: "GET", path: "/v1/agents", group: "agents", summary: "List workspace agents" },
  { method: "POST", path: "/v1/agents", group: "agents", summary: "Create a workspace agent" },
  { method: "GET", path: "/v1/agents/:id", group: "agents", summary: "Get an agent" },
  { method: "DELETE", path: "/v1/agents/:id", group: "agents", summary: "Delete an agent" },
  { method: "GET", path: "/v1/byok", group: "byok", summary: "List org provider keys" },
  { method: "POST", path: "/v1/byok", group: "byok", summary: "Add a provider key" },
  { method: "DELETE", path: "/v1/byok/:id", group: "byok", summary: "Revoke a provider key" },
  { method: "GET", path: "/v1/policies", group: "governance", summary: "List model policies" },
  { method: "POST", path: "/v1/policies", group: "governance", summary: "Create a policy" },
  { method: "GET", path: "/v1/policies/:id", group: "governance", summary: "Get a policy" },
  { method: "PATCH", path: "/v1/policies/:id", group: "governance", summary: "Update a policy" },
  { method: "DELETE", path: "/v1/policies/:id", group: "governance", summary: "Delete a policy" },
] as const;

catalogRouter.get("/", async (c) => {
  const tenant = requireTenant(c);
  if (!tenant) return c.json({ error: "Unauthorized" }, 401);
  return c.json({
    object: "catalog",
    version: "1.0.0",
    auth: "Authorization: Bearer opd_…",
    usage: "Chat, assistants, and workflow LLM steps debit the calling key and org credits.",
    groups: [...new Set(PLATFORM_ENDPOINTS.map((e) => e.group))],
    data: PLATFORM_ENDPOINTS,
  });
});

export default catalogRouter;
